### ISSUE TITLE
Possible typo in README.md 

### ISSUE THREAD

**Issue by SoliareofAstora** [twilk/Kamila#1]
darwin.pl przekierowuje do jakiejś stornki z gierkami. Nie powinno to być darwina.pl?

**Comment by twilk** [comment]
> darwin.pl przekierowuje do jakiejś stornki z gierkami. Nie powinno to być darwina.pl?

yszty kurła XD

dopiero to rzeźbię xD

**Comment by SoliareofAstora** [comment]
Dziękuję za fix <3 <3 <3
